// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5cFT2bblXJqJutDeOxCJz88J2ePnbxwQ',
    appId: '1:403647284227:web:0f5849698acc586c69fa36',
    messagingSenderId: '403647284227',
    projectId: 'fir-challenge02',
    authDomain: 'fir-challenge02.firebaseapp.com',
    storageBucket: 'fir-challenge02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXcHrDGeARF-DgvptfDGa_zI6D3FkHei4',
    appId: '1:403647284227:android:fddf1e091836477e69fa36',
    messagingSenderId: '403647284227',
    projectId: 'fir-challenge02',
    storageBucket: 'fir-challenge02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDx1YNaOKfpzAY9CsE-RNmbPwk197n9KM',
    appId: '1:403647284227:ios:3a081fb91178dd5569fa36',
    messagingSenderId: '403647284227',
    projectId: 'fir-challenge02',
    storageBucket: 'fir-challenge02.appspot.com',
    iosClientId: '403647284227-i991mn8vj6brc5kp2n24v7cklmdct0ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChallenge02',
  );
}
